### PR TITLE
Sandlot

### LINKED ISSUE #19: spack garbage collect when building github cache

### PR DESCRIPTION
**Pull request by idigs**
This fixes #19

### CODE REVIEW

**Comment by quantumsteve** [comment]
@idigs Which of the workflow files is run on pull requests? Are the others necessary?

**Comment by idigs** [comment]
> @idigs Which of the workflow files is run on pull requests? Are the others necessary?

Only the spack.yml workflow is active.  I left the others there as I may need to reference them later.

**Review by quantumsteve — APPROVED** [review]
Let's get this in main and iterate from there.

**Review by mbeidler3 — APPROVED** [review]
Looks good to me!

**Pull request merged**
