### PR TITLE
Refactor and unify the random numbers.

### PR DESCRIPTION
**Pull request by cianciosa**
This unifies and cleans up the random number generation to ensure that random numbers are seeded once at the beginning.

### CODE REVIEW

**Comment by quantumsteve** [comment]
@idigs @cianciosa Do you see an error message from `job_two`?

**Comment by cianciosa** [comment]
> @idigs @cianciosa Do you see an error message from `job_two`?

I'm guessing the test failure is a result of differences in seeding. Do you know if this test uses a constant seed?

**Comment by mbeidler3** [comment]
The initial case I provided may use a different seed than the present case.

**Comment by quantumsteve** [comment]
> > @idigs @cianciosa Do you see an error message from `job_two`?
> 
> I'm guessing the test failure is a result of differences in seeding. Do you know if this test uses a constant seed?

I think it's a Chrome or GitHub issue.

**Comment by quantumsteve** [comment]
image

**Comment by cianciosa** [comment]
I get

Screenshot 2024-05-31 at 2 23 24 PM

**Review by mbeidler3 — COMMENTED** [review]
This is looking pretty good on my computer. When I run it multiple times, I keep getting the same exact results with a good distributions of REs. The only issue is that I am getting different answers compared to what Mark sent me by email on 6/5/24. While the spatial distribution is different.

**Comment by mbeidler3** [comment]
test this please

**Comment by mbeidler3** [comment]
@idigs it looks like the SPACK cache is getting built and created again. Can we set it up a workflow to have this to happen automatically on a weekend evening?

**Comment by mbeidler3** [comment]
test this please

**Comment by mbeidler3** [comment]
@idigs, how long does it usually take for an ExCL runner to pick up the Onyx workflow?

**Review by mbeidler3 — APPROVED** [review]
Didn't do comprehensive testing due to size, but works for mars regression CTest.

**Pull request merged**
