### PR TITLE
Run mars_test on up to 16 processes

### PR DESCRIPTION
**Pull request by quantumsteve**

### CODE REVIEW

**Comment by quantumsteve** [comment]
Test this please

**Comment by mbeidler3** [comment]
test this please

**Comment by quantumsteve** [comment]
Test this please

**Comment by idigs** [comment]
test this please

**Comment by quantumsteve** [comment]
Test this please

**Comment by quantumsteve** [comment]
Failing on ExCL
https://github.com/ORNL-Fusion/KORC/actions/runs/10688374537/job/29628173066

**Comment by mbeidler3** [comment]
test this please

**Pull request merged**
