### PR TITLE
create innocuous_file.txt

### PR DESCRIPTION
**Pull request by idigs**

### CODE REVIEW

**Comment by idigs** [comment]
test this please

**Comment by idigs** [comment]
test this please

**Comment by idigs** [comment]
test this please

**Comment by idigs** [comment]
test this please

**Comment by idigs** [comment]
test this please

**Comment by idigs** [comment]
test this please

**Comment by mbeidler3** [comment]
test this please

**Comment by mbeidler3** [comment]
@idigs, @quantumsteve, @cianciosa On my machine (famous last words), I added all compiler flags from an older case that worked (in branch beidler-new-laptop:build_scripts/build_ne_gpu.sh). Initially, when running cuda-gdb it said that I had no recognized CUDA device. I then updated my CUDA drivers, and a subsequent build ran successfully. I parred down the additional compilation flags to using c++ libraries and "-mp". What I added to this PR was those compiler flags but still got the same error as before.

**Comment by mbeidler3** [comment]
test this please

**Comment by mbeidler3** [comment]
please test the correct commit 4f944a7

**Comment by mbeidler3** [comment]
My last "please test" instead sent main at 95e4c88 to ExCL

**Review by mbeidler3 — APPROVED** [review]
Hopefully this doesn't break everything

**Pull request merged**
